### ISSUE TITLE
Error "The current .NET SDK does not support targeting .NET Core 2.2. "

### ISSUE THREAD

**Issue by it19862** [tonysneed/Demo.DotNetSelfHost#6]
Error "The current .NET SDK does not support targeting .NET Core 2.2. 
 Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2."
![2019-07-13_23-22-29](https://user-images.githubusercontent.com/18245828/61176190-1884af80-a5c5-11e9-8142-28a6e1d3f03c.png)

I installed - sdk 2.2.301
![2019-07-13_23-20-58](https://user-images.githubusercontent.com/18245828/61176183-f2f7a600-a5c4-11e9-824b-472570d46f44.png)

**Installed**
![2019-07-13_23-24-33](https://user-images.githubusercontent.com/18245828/61176206-64375900-a5c5-11e9-8031-a3d1dc513621.png)

`Microsoft Visual Studio Community 2017 
Версия 15.9.14
VisualStudio.15.Release/15.9.14+28307.770
Microsoft .NET Framework
Версия 4.7.03062

Установленная версия: Community

Visual C++ 2017   00369-60000-00001-AA813
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.61435.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.3000.2
Microsoft Azure Data Lake Tools for Visual Studio

Azure Stream Analytics Tools for Visual Studio   2.3.3000.2
Microsoft Azure Stream Analytics Tools for Visual Studio

BusinessObjectEditor   1.0
Information about my package

ConvertToDevExtremeCommand Extension   1.0
ConvertToDevExtremeCommand Visual Studio Extension Detailed Info

Cookiecutter   15.9.18254.1
Предоставляет средства для поиска, создания экземпляров и настройки шаблонов в формате cookiecutter.

Devart dotConnect for SQLite   5.11.1307.0
Devart dotConnect for SQLite
Copyright 2002 - 2019 Devart. All rights reserved.
Web: www.devart.com/dotconnect/sqlite
Support: support@devart.com

Devart Entity Developer   6.3.660.0
Devart Entity Developer
Copyright © 2008-2019 Devart. All rights reserved.
Web: www.devart.com/entitydeveloper 
Support: support@devart.com

DevExpress.ExpressApp.Design.DynamicPackage   1.0
DevExpress VSIX Package

DevExpress.ExpressApp.DesignPackage   1.0
DevExpress VSIX Package

DevExtreme.Design   17.2.7
DevExtreme Visual Studio integration package

Fabric.DiagnosticEvents   1.0
События диагностики Fabric

GitHub.VisualStudio   2.6.0.6193
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure HDInsight Azure Node   2.3.3000.2
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.3000.2
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.3.3000.2
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   15.9.18254.1
Предоставляет IntelliSense, проекты, шаблоны, отладку, интерактивные окна и другие вспомогательные функции для разработчиков Python.

Python — поддержка IronPython   15.9.18254.1
Предоставляет шаблоны и интеграцию для проектов на основе IronPython.

Python — поддержка Django   15.9.18254.1
Предоставляет шаблоны и интеграцию для веб-платформы Django.

Python — поддержка профилирования   15.9.18254.1
Поддержка профилирования для проектов Python.

Quick Diagram Tool for C#   0.5.60
Code visualization tool for C# to quickly explore, navigate and document source code structure and relationships.

RegexTester   1.0
This is regular extension tester.

RegularExpressionExtension Extension   1.0
RegularExpressionExtension Visual Studio Extension Detailed Info

Snippet Designer   1.6.5
Snippet Designer is a Visual Studio plug in which allows you to create and search for snippets inside the IDE

SQL Server Data Tools   15.1.61906.03120
Microsoft SQL Server Data Tools

SQLite & SQL Server Compact Toolbox   4.7
SQLite & SQL Server Compact Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.

Syncfusion Reference Manager   16.1.0.24
A useful add-in for adding and migrating Syncfusion Assembly References for Windows Forms, WPF, and Silverlight projects.

Syncfusion.VSExtension.Troubleshooter   16.1.0.24
Add-in for Troubleshooting the Syncfusion projects.

Telerik WinForms VSExtensions   2018.1.215.2
Progress® Telerik® UI for WinForms Visual Studio extensions

Telerik WPF VSExtensions   2018.1.215.2
Progress® Telerik® UI for WPF Visual Studio extensions

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

Visual F# Tools 10.2 для F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 для F# 4.5

Workflow Manager Tools 1.0   1.0
Этот пакет содержит компоненты, необходимые для интеграции Visual Studio со службой Workflow Manager.

Адаптер теста для Google Test   1.0
Включает средства тестирования Visual Studio и модульные тесты для Google Test.  Условия использования и уведомления сторонних производителей см. в каталоге установки расширения.

Диспетчер пакетов NuGet   4.6.0
Диспетчер пакетов NuGet в Visual Studio. Дополнительную информацию о NuGet см. на веб-сайте http://docs.nuget.org/.

Инструменты Microsoft Azure   2.9
Microsoft Azure Tools для Microsoft Visual Studio 2017 — v2.9.20417.1

Инструменты Node.js   1.4.30613.3 Commit Hash:1e6f79a5385c9083fd034ccdfc4f64f58dea9e7b
Обеспечивает поддержку разработки и отладки приложений Node.js в Visual Studio

Инструменты Visual Studio для CMake   1.0
Инструменты Visual Studio для CMake

Инструменты для Функций Azure и веб-заданий   15.9.03024.0
Инструменты для Функций Azure и веб-заданий

Инструменты непрерывной поставки Microsoft для Visual Studio   0.4
Упрощение настройки конвейеров Azure DevOps из интегрированной среды разработки Visual Studio.

Инструменты разработчика Office для Visual Studio 2017 — RUS   15.0.28224.00
Инструменты разработчика Microsoft Office для Visual Studio 2017 — RUS

Мастера Microsoft Visual C++   1.0
Мастера Microsoft Visual C++

Общие инструменты Windows Azure   1.10
Предоставляет общие службы для использования мобильными службами и инструментами Microsoft Azure.

Пакет VC Microsoft Visual Studio   1.0
Пакет VC Microsoft Visual Studio

Пакет размещения адаптеров отладки Visual Studio Code   1.0
Уровень взаимодействия для размещения адаптеров отладки Visual Studio Code в Visual Studio

Пакет средств Application Insights для Visual Studio   8.14.20131.1
Средства Application Insights для Visual Studio

Расширение ResourcePackage   1.0
Подробные сведения о расширении ResourcePackage для Visual Studio

Расширение ResourcePackage   1.0
Подробные сведения о расширении ResourcePackage для Visual Studio

Средства C#   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Компоненты C#, используемые в среде IDE. В зависимости от типа и параметров проекта может использоваться другая версия компилятора.

Средства Microsoft Azure Service Fabric для Visual Studio   2.5
Средства Microsoft Azure Service Fabric для Visual Studio

Средства Microsoft Visual Studio для контейнеров   1.1
Разработка, запуск и проверка приложений ASP.NET Core в целевой среде. Нажав клавишу F5, можно отправить приложение напрямую в контейнер с отладкой, а клавиши CTRL+F5 позволяют изменить и обновить приложение без повторной сборки контейнера.

Средства TypeScript   15.9.30524.2002
Средства TypeScript для Microsoft Visual Studio

Средства Visual Basic   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Компоненты Visual Basic, используемые в среде IDE. В зависимости от типа и параметров проекта может использоваться другая версия компилятора.

Средства Visual Studio для контейнеров   1.0
Средства Visual Studio для контейнеров

Языковая служба JavaScript   2.0
Языковая служба JavaScript`

**Comment by tonysneed** [comment]
Change the global.json file to match the version of the .NET Core SDK you installed. https://github.com/tonysneed/Demo.DotNetSelfHost/blob/master/global.json From your screenshot this appears to be 2.2.301.

**Comment by it19862** [comment]
@tonysneed 
Changed global.json.
F6.

Error has changed
Error "The current .NET SDK does not support targeting .NET Core 2.2.301. 
 Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2.301."
![2019-07-14_00-01-18](https://user-images.githubusercontent.com/18245828/61176501-8f707700-a5ca-11e9-9c4c-b6c57deec742.png)

**Comment by tonysneed** [comment]
According to the .NET Core [downloads](https://dotnet.microsoft.com/download/dotnet-core/2.2) page, you either need to use .NET Core SDK v2.2.105 with Visual Studio 2017 v15.9, or use .NET Core SDK v2.2.301 with Visual Studio 2019 v16.1.

Unless you have a good reason to use VS 2017, I would recommend upgrading to VS 2019.

**Comment by tonysneed** [comment]
Were you able to resolve this error?

**Comment by it19862** [comment]
@tonysneed 
Installed SDK v2.2.105
Changed global.json
```
{
  "sdk": {
    "version": "2.2.105"
  }
}

```
I get an error:
"The current .NET SDK does not support targeting .NET Core 2.2.301.  
Either target .NET Core 1.1 or lower, 
or use a version of the .NET SDK that supports .NET Core 2.2.301."

If it does not work out to solve the problem, then I will try to install VS 2019
To install the VS 2019 will be in a pinch.
![2019-07-15_23-30-35](https://user-images.githubusercontent.com/18245828/61247309-74803d00-a759-11e9-9b53-8efbecc9d35c.png)

![2019-07-15_23-33-50](https://user-images.githubusercontent.com/18245828/61247290-6f22f280-a759-11e9-9306-5dac51237094.png)

**Comment by tonysneed** [comment]
Installing SDK v2.2.105 and setting the version to match in global.json should resolve the error, which is complaining about v 2.2.301. Make sure to quit and restart VS 2017.  Otherwise try VS 2019. :)

**Comment by it19862** [comment]
@tonysneed 
I have rebooted VS 2017.
The error remained.

For now, leave this problem.

VS 2019 I will install when there will be time

**Comment by tonysneed** [comment]
I was able to replicate the error, then I was able to make the error go away. First I installed VS 2017 on a fresh Windows 10 virtual machine. The version is **15.9.14**.

<img width="770" alt="vs-2017-about" src="https://user-images.githubusercontent.com/2836367/61295180-16754900-a79d-11e9-95e3-555bc0f23b96.png">

Next, I added the **.NET 4.7.2** dev tools.

<img width="1291" alt="vs-2017-install" src="https://user-images.githubusercontent.com/2836367/61295262-3e64ac80-a79d-11e9-8995-cd549db8a759.png">

Next, I installed the **.NET Core SDK 2.2.105** from https://dotnet.microsoft.com/download/dotnet-core/2.2.

<img width="1287" alt="dot-net-2-2-105" src="https://user-images.githubusercontent.com/2836367/61295429-a0251680-a79d-11e9-9c47-09866d86e1b5.png">

At this point I opened **Demo.DotNetSelfHost.sln**. When I built the project, I received the same error you did: 

"The current .NET SDK does not support targeting .NET Core 2.2.301.
Either target .NET Core 1.1 or lower,
or use a version of the .NET SDK that supports .NET Core 2.2.301."

Lastly, I updated **global.json** in the solution folder:

```json
{
  "sdk": {
    "version": "2.2.105"
  }
}
```

At this point, I relaunched Visual Studio and opened **Demo.DotNetSelfHost.sln**. I was able to build the solution without any errors.  If you follow these same steps, you should be able to eliminate the previous build error you encountered.

**Comment by tonysneed** [comment]
@it19862 Does this work for you now? Can I close this issue?
